# Generated by Django 3.2.3 on 2023-07-31 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ingredient_measurement_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='description',
            new_name='text',
        ),
    ]
