# Generated by Django 3.2.3 on 2023-08-03 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230803_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.ingredient'),
            preserve_default=False,
        ),
    ]
