# Generated by Django 3.2.3 on 2023-08-03 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_shopping_ingredient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopping',
            name='ingredient',
        ),
    ]
